# Generated by Django 5.0.7 on 2024-07-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchhistory',
            name='user',
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='session_key',
            field=models.CharField(default=1, max_length=40),
        ),
    ]
