# Generated by Django 5.0.7 on 2024-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_remove_searchhistory_user_searchhistory_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='session_key',
            field=models.CharField(max_length=40),
        ),
    ]
